#!/usr/bin/bash
source ~/.config/panel/panel.cfg
source ~/.config/panel/prepare.sh

PATH="$HOME/bin:$PATH"

# echo a list of herbstluftwm tags, with different colors to indicate focused,
# non-empty, empty, and urgent tags
tags() {
    echo -n "%{U$bwhite}  "
    herbstclient tag_status | sed -re 's/\t([\.:\+#!])([^\t]*)/\1%{A:herbstclient use \2:} \2 %{A}/g' \
        -e "s/[\+#]/%{U$bwhite}/g" \
        -e "s/:%/%{U$white}%/g" \
        -e "s/\./%{U$gray}/g" \
        -e "s/!/%{U$orange}/g"
}

# echo the current battery level, along with an icon to indicate whether the
# battery is charging or on battery power, and a color to indicate how full the
# battery is
bat() {
    lvl=$(cat $bat/capacity 2>/dev/null)
    if [ $? -eq 0 ]; then
        if [ $lvl -gt 60 ]; then
            color="%{U$green}"
        elif [ $lvl -gt 20 ]; then
            color="%{U#$orange}"
        else
            color="%{U$red}"
        fi
        grep -Eq 'Charging|Full' $bat/status && ico="" || ico=""
        echo "$color $ico $lvl% "
    fi
}

# echo the current sound level for the 'Master' control, unless muted; when
# clicked, the associated icon will also toggle muting
vol() {
    volinfo=$(amixer get Master | tail -1)
    if [ $(echo $volinfo | awk '{ print $6 }' | tr -d '[]') = "on" ]; then
        echo -n "%{U$yellow} %{A:amixer set Master mute:}%{A} "
        echo $volinfo | awk '{ print $4 }' | tr -d '[]'
    else
        echo "%{U$brown} %{A:amixer set Master unmute:}%{A} "
    fi
}

clock() {
    date +'%R'
}

while true; do
    echo "%{l+o}$(tags)%{c-o}$(clock)%{r+o}$(vol) %{U-}"
    sleep 0.2
done | $panel | $sh
