#!/bin/bash
source ~/.config/colors/colors.sh

ln -sf "$1" "$HOME/img/desktop"
hsetroot -fill "$HOME/img/desktop" -write "$HOME/img/lock.png"

convert "$HOME/img/lock.png" -blur 0x10 \
	-background none "$HOME/img/lock_icon.png" -gravity center -geometry +0-49 \
	-composite "$HOME/img/lock.png"
