#!/bin/bash
# chkp <id> <profile>
if [[ ! $1 || ! $2 ]]; then
    echo "usage: chkp <id> <profile>"
    exit 1
fi

KEYS_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}/keys"
PROFILE="$KEYS_ROOT/profiles/$1.$2"

mkdir -p "$KEYS_ROOT/extra"
if [ -e "$PROFILE" ]; then
    ln -sf "$PROFILE" "$KEYS_ROOT/extra/$1"
else
    echo -e "\e[1;31merror:\e[0m no such profile: $1@$2"
fi
