#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Fat-Ergo-Data==0.1.0','console_scripts','fed'
__requires__ = 'Fat-Ergo-Data==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('Fat-Ergo-Data==0.1.0', 'console_scripts', 'fed')()
    )
