#!/usr/bin/bash
source $PANEL_HOME/config
j4-dmenu-desktop --term=urxvt --dmenu="dmenu -i -h $height -dim 0.5 -dc '$back_color' -fn 'Inconsolata-g:size=9' -nb '$dnsel_back' -nf '$dnsel_fore' -sb '$dsel_back' -sf '$dsel_fore'"
