#!/bin/bash
source ~/.config/colors/colors.sh
i3lock -i ~/img/lock.png --ringcolor="${white}33" --insidecolor="00000000" \
    --linecolor=00000000 --keyhlcolor="${green}aa" --bshlcolor="${orange}ff" \
    --ringwrongcolor="00000000" --insidewrongcolor="00000000" \
    --ringvercolor="00000000" --insidevercolor="00000000" \
    --textcolor="${white}ff"
