#!/bin/bash
#source ~/.config/colors/colors.sh

i3lock -e -i "$HOME/img/lock.png" --ringcolor="00000000" --insidecolor="00000000" \
    --linecolor="00000000" --keyhlcolor="c85e7cff" --bshlcolor="fdcc59ff" \
    --ringwrongcolor="00000000" --insidewrongcolor="00000000" \
    --ringvercolor="00000000" --insidevercolor="00000000" \
    --wrongcolor="dd464cff" --separatorcolor="00000000" --verifcolor="b9b5b8ff" \
    --veriftext="Checking..." --wrongtext="WRONG" --locktext="Locking..."
