#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'lexis','console_scripts','panick'
__requires__ = 'lexis'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('lexis', 'console_scripts', 'panick')()
    )
