#!/usr/bin/bash
source ~/.config/colors/colors.sh

pidfile="/tmp/pop-pid"

# kill any existing popups
test -e "$pidfile" && pkill -P $(cat "$pidfile")
echo $$ >"$pidfile"

(echo " $@"; sleep 2) | lemonbar -B "#$color19" -bg 480x48+40+40 \
    -f 'Iosevka:size=15:style=Regular' -f 'Material Icons:size=17'
