#!/usr/bin/bash
# pop - send a popup message to a running panel

source $HOME/.local/panel/config

# Kill old instances (to prevent them from sending the empty message
# prematurely)
for pid in $(pidof -x pop); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi
done

send() {
    # Send a message to the panel
    echo "msg$cmd_ifs$1" >> $fifo
}

send "$@"
sleep 2
send
