#!/usr/bin/bash
pidfile="/tmp/pop-pid"

# kill any existing popups
test -e "$pidfile" && pkill -P $(cat "$pidfile")
echo $$ >"$pidfile"

(echo " $@"; sleep 2) | lemonbar -bg ${bargeom:-490x48+40+40} -B${barbg} -F${barfg} \
    -f 'Iosevka:size=15:style=Regular' -f 'Material Icons:size=17'
